---
- name: Restart mongod process
  hosts: all
  tasks:
  - name: Display all facts
    debug:
      var: ansible_facts
  - name: Verify mongo status
    command: "systemctl stop mongod"
    when: (ansible_facts["distribution"] == "OracleLinux")
